
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NOM VERBE DETphrase : GroupeNom VERBE GroupeNomGroupeNom : DET NOM'
    
_lr_action_items = {'$end':([1,5,6,],[0,-2,-1,]),'NOM':([3,],[5,]),'VERBE':([2,5,],[4,-2,]),'DET':([0,4,],[3,3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'phrase':([0,],[1,]),'GroupeNom':([0,4,],[2,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> phrase","S'",1,None,None,None),
  ('phrase -> GroupeNom VERBE GroupeNom','phrase',3,'p_phrase','grammaire NLP.py',46),
  ('GroupeNom -> DET NOM','GroupeNom',2,'p_GroupeNominal','grammaire NLP.py',51),
]
